# Generated by Django 3.2 on 2023-04-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
